const MoviesAPIData = {
  page: 1,
  results: [
    {
      backdrop_path: '/fY3lD0jM5AoHJMunjGWqJ0hRteI.jpg',
      id: 940721,
      original_title: 'ゴジラ-1.0',
      overview:
        'In postwar Japan, Godzilla brings new devastation to an already scorched landscape. With no military intervention or government help in sight, the survivors must join together in the face of despair and fight back against an unrelenting horror.',
      poster_path: '/hkxxMIGaiCTmrEArK7J56JTKUlB.jpg',
      media_type: 'movie',
      adult: false,
      title: 'Godzilla Minus One',
      original_language: 'ja',
      genre_ids: [878, 27, 28],
      popularity: 718.691,
      release_date: '2023-11-03',
      video: false,
      vote_average: 7.657,
      vote_count: 1255,
    },
    {
      backdrop_path: '/tkHQ7tnYYUEnqlrKuhufIsSVToU.jpg',
      id: 437342,
      original_title: 'The First Omen',
      overview:
        'When a young American woman is sent to Rome to begin a life of service to the church, she encounters a darkness that causes her to question her own faith and uncovers a terrifying conspiracy that hopes to bring about the birth of evil incarnate.',
      poster_path: '/uGyiewQnDHPuiHN9V4k2t9QBPnh.jpg',
      media_type: 'movie',
      adult: false,
      title: 'The First Omen',
      original_language: 'en',
      genre_ids: [27],
      popularity: 1667.008,
      release_date: '2024-04-03',
      video: false,
      vote_average: 6.799,
      vote_count: 276,
    },
    {
      backdrop_path: '/oavbmL3iddJUmC8nQjL6bLHwAP4.jpg',
      id: 719221,
      original_title: 'Tarot',
      overview:
        'When a group of friends recklessly violate the sacred rule of Tarot readings, they unknowingly unleash an unspeakable evil trapped within the cursed cards. One by one, they come face to face with fate and end up in a race against death.',
      poster_path: '/gAEUXC37vl1SnM7PXsHTF23I2vq.jpg',
      media_type: 'movie',
      adult: false,
      title: 'Tarot',
      original_language: 'en',
      genre_ids: [27, 53],
      popularity: 2019.501,
      release_date: '2024-05-01',
      video: false,
      vote_average: 6.464,
      vote_count: 206,
    },
    {
      backdrop_path: '/shrwC6U8Bkst9T9J7fr1A50n6x6.jpg',
      id: 786892,
      original_title: 'Furiosa: A Mad Max Saga',
      overview:
        'As the world fell, young Furiosa is snatched from the Green Place of Many Mothers and falls into the hands of a great Biker Horde led by the Warlord Dementus. Sweeping through the Wasteland they come across the Citadel presided over by The Immortan Joe. While the two Tyrants war for dominance, Furiosa must survive many trials as she puts together the means to find her way home.',
      poster_path: '/iADOJ8Zymht2JPMoy3R7xceZprc.jpg',
      media_type: 'movie',
      adult: false,
      title: 'Furiosa: A Mad Max Saga',
      original_language: 'en',
      genre_ids: [28, 12, 878],
      popularity: 1073.275,
      release_date: '2024-05-22',
      video: false,
      vote_average: 7.741,
      vote_count: 553,
    },
    {
      backdrop_path: '/z121dSTR7PY9KxKuvwiIFSYW8cf.jpg',
      id: 929590,
      original_title: 'Civil War',
      overview:
        'In the near future, a group of war journalists attempt to survive while reporting the truth as the United States stands on the brink of civil war.',
      poster_path: '/sh7Rg8Er3tFcN9BpKIPOMvALgZd.jpg',
      media_type: 'movie',
      adult: false,
      title: 'Civil War',
      original_language: 'en',
      genre_ids: [10752, 28, 18],
      popularity: 2953.978,
      release_date: '2024-04-10',
      video: false,
      vote_average: 7.188,
      vote_count: 1121,
    },
    {
      backdrop_path: '/3TNSoa0UHGEzEz5ndXGjJVKo8RJ.jpg',
      id: 614933,
      original_title: 'Atlas',
      overview:
        'A brilliant counterterrorism analyst with a deep distrust of AI discovers it might be her only hope when a mission to capture a renegade robot goes awry.',
      poster_path: '/bcM2Tl5HlsvPBnL8DKP9Ie6vU4r.jpg',
      media_type: 'movie',
      adult: false,
      title: 'Atlas',
      original_language: 'en',
      genre_ids: [878, 28],
      popularity: 2334.605,
      release_date: '2024-05-23',
      video: false,
      vote_average: 6.708,
      vote_count: 477,
    },
    {
      backdrop_path: '/H5HjE7Xb9N09rbWn1zBfxgI8uz.jpg',
      id: 746036,
      original_title: 'The Fall Guy',
      overview:
        'Fresh off an almost career-ending accident, stuntman Colt Seavers has to track down a missing movie star, solve a conspiracy and try to win back the love of his life while still doing his day job.',
      poster_path: '/tSz1qsmSJon0rqjHBxXZmrotuse.jpg',
      media_type: 'movie',
      adult: false,
      title: 'The Fall Guy',
      original_language: 'en',
      genre_ids: [28, 35],
      popularity: 1538.371,
      release_date: '2024-04-24',
      video: false,
      vote_average: 7.329,
      vote_count: 912,
    },
    {
      backdrop_path: '/xOMo8BRK7PfcJv9JCnx7s5hj0PX.jpg',
      id: 693134,
      original_title: 'Dune: Part Two',
      overview:
        'Follow the mythic journey of Paul Atreides as he unites with Chani and the Fremen while on a path of revenge against the conspirators who destroyed his family. Facing a choice between the love of his life and the fate of the known universe, Paul endeavors to prevent a terrible future only he can foresee.',
      poster_path: '/czembW0Rk1Ke7lCJGahbOhdCuhV.jpg',
      media_type: 'movie',
      adult: false,
      title: 'Dune: Part Two',
      original_language: 'en',
      genre_ids: [878, 12],
      popularity: 836.038,
      release_date: '2024-02-27',
      video: false,
      vote_average: 8.168,
      vote_count: 4248,
    },
    {
      backdrop_path: '/gGW1Je4CaAc1m5QEre6WjA97VKP.jpg',
      id: 1127108,
      original_title: 'En del av dig',
      overview:
        'A teenager struggles to pick up the pieces of her shattered world in this emotional and bittersweet coming-of-age drama about those who are left behind.',
      poster_path: '/rv3FLJ4kLoeFpL6sLSB3tCWLO9f.jpg',
      media_type: 'movie',
      adult: false,
      title: 'A Part of You',
      original_language: 'sv',
      genre_ids: [18],
      popularity: 47.039,
      release_date: '2024-05-31',
      video: false,
      vote_average: 6.9,
      vote_count: 4,
    },
    {
      backdrop_path: '/4CcUgdiGe83MeqJW1NyJVmZqRrF.jpg',
      id: 937287,
      original_title: 'Challengers',
      overview:
        'Tennis player turned coach Tashi has taken her husband, Art, and transformed him into a world-famous Grand Slam champion. To jolt him out of his recent losing streak, she signs him up for a "Challenger" event — close to the lowest level of pro tournament — where he finds himself standing across the net from his former best friend and Tashi\'s former boyfriend.',
      poster_path: '/H6vke7zGiuLsz4v4RPeReb9rsv.jpg',
      media_type: 'movie',
      adult: false,
      title: 'Challengers',
      original_language: 'en',
      genre_ids: [10749, 18],
      popularity: 447.838,
      release_date: '2024-04-18',
      video: false,
      vote_average: 7.283,
      vote_count: 830,
    },
    {
      backdrop_path: '/k9X79JC2dDTcSpxuKJ3p2Teq3oZ.jpg',
      id: 1025463,
      original_title: 'Biônicos',
      overview:
        'When the progress of robotics makes Paralympic athletes the new sports stars, Maria dreams of competing against her sister. For that, she will have to enter a world of crime and violence.',
      poster_path: '/xVCYzdBE6lo3sUFK1OMZnXvpGtT.jpg',
      media_type: 'movie',
      adult: false,
      title: 'Bionic',
      original_language: 'pt',
      genre_ids: [878, 28, 12],
      popularity: 165.052,
      release_date: '2024-05-28',
      video: false,
      vote_average: 5.519,
      vote_count: 26,
    },
    {
      backdrop_path: '/cLXvsCO4KfWSLaXPnJF9GL0NKeg.jpg',
      id: 1115395,
      original_title: 'Kolory zła: Czerwień',
      overview:
        "When a girl's body is found on a beach in Poland's Tricity, a prosecutor teams up with the victim's mother on an impassioned quest for the truth.",
      poster_path: '/5NAdIXaF2AhewMFMqFvbxZmDC3M.jpg',
      media_type: 'movie',
      adult: false,
      title: 'Colors of Evil: Red',
      original_language: 'pl',
      genre_ids: [9648, 53, 80, 18],
      popularity: 89.603,
      release_date: '2024-05-29',
      video: false,
      vote_average: 6.707,
      vote_count: 29,
    },
    {
      backdrop_path: '/pxJbfnMIQQxCrdeLD0zQnWr6ouL.jpg',
      id: 1077280,
      original_title: 'Die Hart',
      overview:
        'Kevin Hart - playing a version of himself - is on a death-defying quest to become an action star. And with a little help from John Travolta, Nathalie Emmanuel, and Josh Hartnett - he just might pull it off.',
      poster_path: '/ff9iMXJjtRdm58nRzM88sNr5CTu.jpg',
      media_type: 'movie',
      adult: false,
      title: 'Die Hart',
      original_language: 'en',
      genre_ids: [35, 28, 53],
      popularity: 149.999,
      release_date: '2023-02-22',
      video: false,
      vote_average: 5.936,
      vote_count: 389,
    },
    {
      backdrop_path: '/qrGtVFxaD8c7et0jUtaYhyTzzPg.jpg',
      id: 823464,
      original_title: 'Godzilla x Kong: The New Empire',
      overview:
        'Following their explosive showdown, Godzilla and Kong must reunite against a colossal undiscovered threat hidden within our world, challenging their very existence – and our own.',
      poster_path: '/z1p34vh7dEOnLDmyCrlUVLuoDzd.jpg',
      media_type: 'movie',
      adult: false,
      title: 'Godzilla x Kong: The New Empire',
      original_language: 'en',
      genre_ids: [878, 28, 12],
      popularity: 2541.848,
      release_date: '2024-03-27',
      video: false,
      vote_average: 7.25,
      vote_count: 2389,
    },
    {
      backdrop_path: '/1m1rXopfNDVL3UMiv6kriYaJ3yE.jpg',
      id: 882059,
      original_title: 'Boy Kills World',
      overview:
        'When his family is murdered, a deaf-mute named Boy escapes to the jungle and is trained by a mysterious shaman to repress his childish imagination and become an instrument of death.',
      poster_path: '/25JskXmchcYwj3jHRmcPm738MpB.jpg',
      media_type: 'movie',
      adult: false,
      title: 'Boy Kills World',
      original_language: 'en',
      genre_ids: [28, 53, 80, 878],
      popularity: 1199.941,
      release_date: '2024-04-24',
      video: false,
      vote_average: 6.875,
      vote_count: 160,
    },
    {
      backdrop_path: '/fqv8v6AycXKsivp1T5yKtLbGXce.jpg',
      id: 653346,
      original_title: 'Kingdom of the Planet of the Apes',
      overview:
        "Several generations in the future following Caesar's reign, apes are now the dominant species and live harmoniously while humans have been reduced to living in the shadows. As a new tyrannical ape leader builds his empire, one young ape undertakes a harrowing journey that will cause him to question all that he has known about the past and to make choices that will define a future for apes and humans alike.",
      poster_path: '/gKkl37BQuKTanygYQG1pyYgLVgf.jpg',
      media_type: 'movie',
      adult: false,
      title: 'Kingdom of the Planet of the Apes',
      original_language: 'en',
      genre_ids: [878, 12, 28],
      popularity: 8377.115,
      release_date: '2024-05-08',
      video: false,
      vote_average: 7,
      vote_count: 719,
    },
    {
      backdrop_path: '/9az3E8loGzTYazvLvoEWI7Flu3M.jpg',
      id: 1108354,
      original_title: 'Kali',
      overview: '',
      poster_path: '/5pn4NnJCd8LKomglJC3gr9DbvYk.jpg',
      media_type: 'movie',
      adult: false,
      title: 'Kali',
      original_language: 'fr',
      genre_ids: [28, 53, 12],
      popularity: 47.46,
      release_date: '2024-05-31',
      video: false,
      vote_average: 5,
      vote_count: 2,
    },
    {
      backdrop_path: '/gqrnQA6Xppdl8vIb2eJc58VC1tW.jpg',
      id: 76341,
      original_title: 'Mad Max: Fury Road',
      overview:
        'An apocalyptic story set in the furthest reaches of our planet, in a stark desert landscape where humanity is broken, and most everyone is crazed fighting for the necessities of life. Within this world exist two rebels on the run who just might be able to restore order.',
      poster_path: '/hA2ple9q4qnwxp3hKVNhroipsir.jpg',
      media_type: 'movie',
      adult: false,
      title: 'Mad Max: Fury Road',
      original_language: 'en',
      genre_ids: [28, 12, 878],
      popularity: 453.216,
      release_date: '2015-05-13',
      video: false,
      vote_average: 7.597,
      vote_count: 21825,
    },
    {
      backdrop_path: '/fRIzLAIlhRc1QKe8lpXOcdmmfHJ.jpg',
      id: 998846,
      original_title: 'Back to Black',
      overview:
        'The extraordinary story of Amy Winehouse’s early rise to fame from her early days in Camden through the making of her groundbreaking album, Back to Black that catapulted Winehouse to global fame. Told through Amy’s eyes and inspired by her deeply personal lyrics, the film explores and embraces the many layers of the iconic artist and the tumultuous love story at the center of one of the most legendary albums of all time.',
      poster_path: '/xHQEeUT3Ac4fTY72UeNrI75xLtE.jpg',
      media_type: 'movie',
      adult: false,
      title: 'Back to Black',
      original_language: 'en',
      genre_ids: [10402, 18],
      popularity: 159.538,
      release_date: '2024-04-11',
      video: false,
      vote_average: 6.7,
      vote_count: 161,
    },
  ],
  total_pages: 1000,
  total_results: 20000,
};
